package com.typ.adaptivestartingstructure.planner;

public enum CoarseRejectionReason {
    AREA_OUTSIDE_WORLD_LIMITS,
    OUTSIDE_WORLD_BORDER,
    INVALID_TERRAIN_HEIGHT,
    ELEVATION_RANGE_EXCEEDED,
    EXCLUDED_BIOME,
    UNLISTED_BIOME,
    LAVA_OR_UNSUPPORTED_FLUID,
    WATER_FRACTION_EXCEEDED,
    STRUCTURE_OUTSIDE_BUILD_HEIGHT
}
