package com.typ.adaptivestartingstructure.planner;

public enum FineRejectionReason {
    EMPTY_FOOTPRINT,
    AREA_OUTSIDE_WORLD_LIMITS,
    OUTSIDE_WORLD_BORDER,
    INVALID_TERRAIN_HEIGHT,
    EXCLUDED_BIOME,
    UNLISTED_BIOME,
    ELEVATION_RANGE_EXCEEDED,
    CUT_DEPTH_EXCEEDED,
    FILL_DEPTH_EXCEEDED,
    PERIMETER_ERROR_EXCEEDED,
    WATER_FRACTION_EXCEEDED,
    LAVA_OR_UNSUPPORTED_FLUID,
    STRUCTURE_OUTSIDE_BUILD_HEIGHT
}
